# Generated by Django 4.0.4 on 2022-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(to='Blog.categoria'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
