# Generated by Django 4.0.4 on 2022-07-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_publicacion_categorias_alter_publicacion_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
